name: Go build/test
on: [push, pull_request]
jobs:
  build_lint_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Go compiler
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Build binary
        run: |
          go build
      - name: Go test
        run: |
          go test -v ./...
          go test -cpu=2 -race -v ./...
