name: Go build/test
on: [push, pull_request]
jobs:
  build_lint_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Go compiler
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
          check-latest: true
      - name: Build binary
        run: |
          make
      - name: Go test
        run: |
          go test -v ./...
          go test -cpu=2 -race -v ./...
